cat-app/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cat-app/app/models/cat.rb
class Cat < ApplicationRecord
end

cat-app/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.create(cat_params)

    redirect_to cats_path(@cat)
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)

    redirect_to cats_path(@cat)
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    redirect_to cats_path
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :description)
  end
end

cat-app/app/helpers/cats_helper.rb
module CatsHelper
end

cat-app/app/views/cats/edit.html.erb
<h3>Edit a Cat</h3>
<%= form_for @cat do |f| %>
  <p>Cat Name: <%= f.text_field :name %></p>
  <p>Cat Description: <%= f.text_field :description %></p>

  <%= f.submit %>
<% end %>

cat-app/app/views/cats/index.html.erb
<table>
  <% @cats.each do |cat| %>
    <tr>
      <td><%= link_to cat.name, cat_path(cat) %></td>
      <td><%= link_to 'edit', edit_cat_path(cat), method: :get %></td>
      <td><%= link_to "Destroy", cat_path(cat), method: "delete", data: {confirm: 'Are you sure'} %></td>
  <% end %>
</table>
<%= link_to "Add", new_cat_path %>

cat-app/app/views/cats/new.html.erb
<h3>Create a New Cat</h3>

<%= form_with model: @cat do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :description, placeholder: "description" %>

  <%= form.submit %>
<% end %>

cat-app/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<h4>"<%= @cat.description %>"</h4>

cat-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>